CREATE DATABASE LMS

GO

USE LMS

GO

CREATE TABLE DEPARTMENT(
	DEPT_ID INT IDENTITY(1,1) PRIMARY KEY
	,DEPT_NAME VARCHAR(50) NOT NULL
	,DEPT_HEAD INT NULL
)

GO


CREATE TABLE JOB_TITLE(
	JOB_TITLE_ID INT IDENTITY(1,1) PRIMARY KEY
	,JOB_TITLE_NAME VARCHAR(50) NOT NULL
	,DEPT_ID INT NOT NULL FOREIGN KEY REFERENCES DEPARTMENT(DEPT_ID)
)

GO

CREATE TABLE EMPLOYEE(
	EMP_ID INT IDENTITY(1,1) PRIMARY KEY
	,EMP_FIRST_NAME VARCHAR(100) NOT NULL
	,EMP_MIDDLE_NAME VARCHAR(100) NULL
	,EMP_LAST_NAME VARCHAR(100) NOT NULL
	,EMAIL VARCHAR(100) NOT NULL
	,JOB_TITLE INT NOT NULL FOREIGN KEY REFERENCES JOB_TITLE(JOB_TITLE_ID)
	,EMP_PASSWORD VARCHAR(100) NOT NULL
)

GO

CREATE TABLE DEPT_SUPERVISOR(
	DEPT_ID INT NOT NULL FOREIGN KEY REFERENCES DEPARTMENT(DEPT_ID)
	,SUPERVISOR INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID)
)

GO

CREATE TABLE LEAVE(
	LEAVE_ID INT IDENTITY(1,1) PRIMARY KEY 
	,LEAVE_NAME VARCHAR(50) NOT NULL
	,LEAVE_HOUR INT NOT NULL
	,LEAVE_COUNT FLOAT NOT NULL
)

GO

CREATE TABLE LEAVE_TYPE(
	LEAVE_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY
	,LEAVE_TYPE VARCHAR(100) NOT NULL
)

GO

CREATE TABLE T_LEAVE(
	T_LEAVE_ID INT IDENTITY(1,1) PRIMARY KEY
	,T_LEAVE_NO AS 'L-' + REPLICATE('0',6-LEN(T_LEAVE_ID)) + CAST(T_LEAVE_ID AS VARCHAR)
	,T_LEAVE INT NOT NULL FOREIGN KEY REFERENCES LEAVE(LEAVE_ID)
	,T_LEAVE_TYPE INT NOT NULL FOREIGN KEY REFERENCES LEAVE_TYPE(LEAVE_TYPE_ID)
	,REASON VARCHAR(MAX) NOT NULL
	,START_DATE DATE NOT NULL
	,END_DATE DATE NOT NULL
	,EMP INT NOT NULL FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID)
	,SUPERVISOR INT NULL FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID)
	,DEPT_HEAD INT NULL FOREIGN KEY REFERENCES EMPLOYEE(EMP_ID)
	,SUPERVISOR_APPROVAL INT NULL
	,DEPT_HEAD_APPROVAL INT NULL
	,STATUS VARCHAR(50) NULL
	,FILE_DATE DATETIME NOT NULL DEFAULT GETDATE()
)

GO

ALTER TABLE DEPARTMENT ADD FOREIGN KEY (DEPT_HEAD )REFERENCES EMPLOYEE(EMP_ID)

GO

ALTER TABLE DEPARTMENT ADD FOREIGN KEY (DEPT_SUPERVISOR)REFERENCES EMPLOYEE(EMP_ID)
